---
- name: Configurar servidores Ubuntu
  hosts: servidores
  become: yes

  tasks:
    - name: Actualizar paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Crear usuario itla
      user:
        name: itla
        state: present
        shell: /bin/bash

    - name: Crear carpeta /home/itla/app
      file:
        path: /home/itla/app
        state: directory
        owner: itla
        group: itla
        mode: '0755'

    - name: Crear archivo hola.txt
      copy:
        dest: /home/itla/app/hola.txt
        content: "Hola desde Ansible 👋"
        owner: itla
        group: itla
        mode: '0644'

    - name: Instalar paquetes cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present
        update_cache: yes

    - name: Agregar /usr/games al PATH de itla
      lineinfile:
        path: /home/itla/.bashrc
        line: 'export PATH=$PATH:/usr/games'
        create: yes
        state: present
      become: yes
      become_user: root

    - name: Cambiar propietario de .bashrc a itla
      file:
        path: /home/itla/.bashrc
        owner: itla
        group: itla
        mode: '0644'
      become: yes
      become_user: root
